### ISSUE TITLE
UI (sometimes) throws error while retrieving project parameters

### ISSUE THREAD

**Issue by otsakir** [RestComm/visual-designer#350]
The issue occurs only on cloud. 

angular.min.js:107 TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (https://cloud.restcomm.com/restcomm-rvd/assets/designer.ac5dc7f6716a69fe.js:406:38)
    at e (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:39:193)
    at Object.instantiate (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:39:310)
    at https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:80:313
    at https://cloud.restcomm.com/restcomm-rvd/js/lib/angular-ui-router/angular-ui-router.js:4081:28
    at aa (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:73:90)
    at K (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:62:39)
    at g (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:54:410)
    at https://cloud.restcomm.com/restcomm-rvd/js/lib/angular.min.js:53:480
    at updateView (https://cloud.restcomm.com/restcomm-rvd/js/lib/angular-ui-router/angular-ui-router.js:4021:23) <div ui-view="container" class="ng-scope">

**Comment by otsakir** [comment]
This proved to be a sync issue that sometimes happens when  a resource takes too long to load. In this case projectParameters. We need to condition further processing on the promise returned by this resource.
